### PR TITLE
Fix/new widget path

### PR DESCRIPTION
**Pull request by HadleyKing**
From @corburn:
The goal of this pull request is to introduce automated testing and potentially make local development easier.

The [.github/workflows/test-integration.yaml](.github/workflows/test-integration.yaml) file is understood by Github as [Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions) to run every time code is pushed to the repository. It will use `docker-compose` to install/configure mongo/apache and use [puppeteer](https://pptr.dev/) to control a Chrome web browser simulating a user registering an account, logging in, and navigating to the BCO editor. An example of this can be found [here](https://github.com/corburn/bco_editor/commit/7d9f4fabd8761d3e77ad9fc3318b226a388a0be1/checks?check_suite_id=315819148).

The environment can be tested locally on a computer with [docker installed](https://docs.docker.com/install/#supported-platforms) by replacing 'localhost' with 'mongo' in the cgi-bin/conf/config.json and running `docker-compose up` in the same directory as the docker-compose.yaml file. The server logs will be printed to the terminal. With the  the `-d` flag, docker-compose will run them as daemons in the background. After it starts you will be able to access the server from http://localhost:8080/bco_editor. The server code is mounted inside the apache container so changes will be applied immediately.

The initdb.d/user.js file is read by the mongo container when the database is first initialized to create the database user.

The Dockerfile is used to create the apache container. The path to the Dockerfile is implied in the docker-compose.yaml by the `build: ./` property.

The requirements.txt file is used in the Dockerfile to install the python dependencies.

The example*.js files are used at the end of the test-integration.yaml to control the Chrome browser.

If you're interested in these changes I'm happy to answer any questions.

### CODE REVIEW

**Comment by corburn** [comment]
The integration test failed because the register button was not found when it opened the site in a Chrome browser. We'll have to run `docker-compose up` and go to `localhost:8080/bco_editor` in a web browser to see what happened.

**Comment by HadleyKing** [comment]
> The integration test failed because the register button was not found when it opened the site in a Chrome browser. We'll have to run `docker-compose up` and go to `localhost:8080/bco_editor` in a web browser to see what happened.

Im meeting today with our vendor today about a new version that uses react. so dont put any time into it if it wont work with react.

**Comment by corburn** [comment]
@HadleyKing React is just a Javascript framework. This is more generic reproducing the installation environment (with Docker) and remote controlling a Chrome browser (with puppeteer) to replicate any action the user would perform by hand. The vendor may have better ideas. These changes (#56) were thrown together over a weekend to simplify the setup/development process/instructions and add any kind of automated testing.

The `master` branch contains existing issues such as git merge conflict markers:

https://github.com/biocompute-objects/bco_editor/blob/36727d62718c8e004daaaaccfb4f22b173d29dce/cgi-bin/bco_editor#L447-L449

The #56 change were applied to the `fix/new widget path` branch based on seeing with `git log --oneline --graph --decorate --all` it was the active development branch.

**Comment by HadleyKing** [comment]
@corburn I was just trying to merge everything quick and dirty to archive this version and move to v 3.0. @openbox-bio suggested we start a completely new repo but I wanted to keep this one for provenance.

**Comment by HadleyKing** [comment]
Created a new [dev](https://github.com/biocompute-objects/bco_editor/tree/dev) branch where this code has been merged so I am closing this pull. We will move into master from there.

**Pull request closed without merging**
